"""HTML reporter, a self-contained, styled report.

Produces a single HTML file with all CSS inlined (no external assets), so it can
be opened directly, emailed, or published as a CI artifact. The same data drives
the web dashboard; this is the static, shareable rendering of one scan.
"""

from __future__ import annotations

import html as html_lib

from argus.core.models import ScanResult, Severity
from argus.core.plugin import Reporter, reporter

_SEV_COLOR = {
    Severity.CRITICAL: "#b4232c",
    Severity.HIGH: "#d9822b",
    Severity.MEDIUM: "#c9a227",
    Severity.LOW: "#3b7dd8",
    Severity.INFO: "#6b7280",
}


def _esc(text: str) -> str:
    return html_lib.escape(text or "")


@reporter
class HTMLReporter(Reporter):
    name = "html"
    extension = "html"
    description = "Self-contained styled HTML report."

    def render(self, result: ScanResult) -> str:
        s = result.project_summary
        findings = result.sorted_findings()
        cards = "\n".join(self._card(i, f) for i, f in enumerate(findings, 1))
        if not findings:
            cards = ('<p class="empty">No findings at or above the configured '
                     'severity threshold.</p>')

        return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Argus Report, {_esc(s.get('name', result.target))}</title>
<style>{_CSS}</style>
</head>
<body>
<header>
  <div class="wrap">
    <h1>Argus Security Report</h1>
    <p class="sub">{_esc(s.get('name', result.target))}</p>
  </div>
</header>
<main class="wrap">
  {self._summary(result)}
  <h2>Findings <span class="muted">({len(findings)})</span></h2>
  {cards}
  <footer>Generated by Argus v{_esc(result.argus_version)} ·
    Attack simulations are produced in an isolated context; no live target was
    contacted.</footer>
</main>
</body>
</html>"""

    def _summary(self, result: ScanResult) -> str:
        s = result.project_summary
        counts = result.counts_by_severity()
        chips = "".join(
            f'<div class="chip" style="--c:{_SEV_COLOR[Severity.parse(label.upper())]}">'
            f'<span class="n">{n}</span><span class="l">{label}</span></div>'
            for label, n in counts.items()
        )
        arch = s.get("architecture", {}) or {}
        facts = []
        for label, key in [("Languages", "languages"), ("Frameworks", "frameworks"),
                           ("APIs", "apis"), ("Datastores", "datastores"),
                           ("Cloud", "cloud")]:
            val = s.get(key) or arch.get(key)
            if isinstance(val, dict):
                val = ", ".join(val.keys())
            elif isinstance(val, list):
                val = ", ".join(val)
            if val:
                facts.append(f"<tr><th>{label}</th><td>{_esc(str(val))}</td></tr>")
        risk = result.aggregate_risk()
        return f"""
  <section class="summary">
    <div class="gauge">
      <div class="score" style="--r:{risk}">{risk}</div>
      <div class="score-label">Aggregate risk / 100</div>
    </div>
    <div class="chips">{chips}</div>
    <table class="facts">{''.join(facts)}</table>
  </section>"""

    def _card(self, index: int, f) -> str:
        color = _SEV_COLOR.get(f.severity, "#6b7280")
        snippet = (f'<pre class="code">{_esc(f.location.snippet)}</pre>'
                   if f.location.snippet else "")
        blocks = []
        for label, val in [
            ("Why it's a vulnerability", f.why_vulnerable),
            ("How an attacker exploits it", f.attacker_perspective),
            ("Business impact", f.business_impact),
        ]:
            if val:
                blocks.append(f'<p><strong>{label}:</strong> {_esc(val)}</p>')

        exploit = self._exploit(f.exploit) if f.exploit else ""
        remediation = self._remediation(f.remediation) if f.remediation else ""
        mapping = ", ".join(f.cwe + f.owasp)

        return f"""
  <article class="finding" style="--c:{color}">
    <div class="fhead">
      <span class="badge" style="background:{color}">{f.severity.label}</span>
      <h3>{index}. {_esc(f.title)}</h3>
    </div>
    <div class="meta">
      <span>Risk {f.risk_score()}/100</span>
      <span>Confidence {f.confidence.label}</span>
      <span>Likelihood {f.likelihood.label}</span>
      <span class="mono">{_esc(f.location.as_ref())}</span>
      <span class="mono">{_esc(f.rule_id)}</span>
    </div>
    {f'<div class="mapping">{_esc(mapping)}</div>' if mapping else ''}
    {snippet}
    {''.join(blocks)}
    {exploit}
    {remediation}
  </article>"""

    def _exploit(self, ex) -> str:
        rows = [
            ("Discovery", ex.discovery),
            ("Walkthrough", ex.exploit_walkthrough),
            ("Data at risk", ex.data_at_risk),
            ("How the fix blocks it", ex.fix_blocks_attack),
            ("Before / after", ex.before_after),
        ]
        items = "".join(f"<li><strong>{label}:</strong> {_esc(val)}</li>"
                        for label, val in rows if val)
        return f"""
    <details class="sim"><summary>🎯 Attack simulation</summary>
      <ul>{items}</ul>
    </details>"""

    def _remediation(self, rem) -> str:
        patch = ""
        if rem.patch:
            status = "verified ✓" if rem.verified else "proposed"
            patch = (f'<div class="patch-status">Patch ({status})</div>'
                     f'<pre class="patch">{_esc(rem.patch)}</pre>')
        guidance = (f"<p>{_esc(rem.guidance)}</p>"
                    if rem.guidance and rem.guidance != rem.summary else "")
        return f"""
    <div class="rem">
      <strong>Remediation:</strong> {_esc(rem.summary)}
      {guidance}
      {patch}
    </div>"""


_CSS = """
:root { color-scheme: light dark; --bg:#f6f7f9; --card:#fff; --fg:#1a1d23;
  --muted:#6b7280; --border:#e3e6ea; --mono:#f0f2f5; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#0f1216; --card:#181c22; --fg:#e6e9ee; --muted:#9aa4b2;
    --border:#262b33; --mono:#11151a; } }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
  font: 15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,sans-serif; }
.wrap { max-width: 960px; margin: 0 auto; padding: 0 20px; }
header { background: linear-gradient(120deg,#1f2937,#111827); color:#fff;
  padding: 28px 0; }
header h1 { margin:0; font-size: 22px; letter-spacing:.3px; }
header .sub { margin:4px 0 0; opacity:.8; }
main { padding: 24px 20px 60px; }
h2 { margin-top: 32px; }
.muted { color: var(--muted); font-weight: normal; }
.summary { display:flex; gap:20px; flex-wrap:wrap; align-items:center;
  background:var(--card); border:1px solid var(--border); border-radius:12px;
  padding:20px; margin-top:16px; }
.gauge { text-align:center; }
.score { font-size:34px; font-weight:700; }
.score-label { font-size:12px; color:var(--muted); }
.chips { display:flex; gap:10px; flex-wrap:wrap; }
.chip { display:flex; flex-direction:column; align-items:center; min-width:64px;
  padding:8px 10px; border-radius:10px; border:1px solid var(--border);
  border-top:3px solid var(--c); }
.chip .n { font-size:20px; font-weight:700; }
.chip .l { font-size:11px; color:var(--muted); }
.facts { border-collapse:collapse; font-size:13px; }
.facts th { text-align:left; color:var(--muted); padding:2px 12px 2px 0;
  font-weight:600; vertical-align:top; }
.facts td { padding:2px 0; }
.finding { background:var(--card); border:1px solid var(--border);
  border-left:4px solid var(--c); border-radius:10px; padding:16px 18px;
  margin:14px 0; }
.fhead { display:flex; align-items:center; gap:10px; }
.fhead h3 { margin:0; font-size:16px; }
.badge { color:#fff; font-size:11px; font-weight:700; padding:2px 8px;
  border-radius:20px; text-transform:uppercase; letter-spacing:.4px; }
.meta { display:flex; gap:14px; flex-wrap:wrap; color:var(--muted);
  font-size:12px; margin:8px 0; }
.mono, .mapping { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; }
.mapping { font-size:12px; color:var(--muted); margin-bottom:8px; }
.code, .patch { background:var(--mono); border:1px solid var(--border);
  border-radius:8px; padding:10px 12px; overflow-x:auto; font-size:12.5px;
  font-family: ui-monospace,SFMono-Regular,Menlo,monospace; }
.rem { background:var(--mono); border-radius:8px; padding:12px 14px;
  margin-top:10px; }
.patch-status { font-size:12px; color:var(--muted); margin:8px 0 4px; }
.sim { margin:10px 0; }
.sim summary { cursor:pointer; font-weight:600; }
.sim ul { margin:8px 0 0; padding-left:18px; }
.sim li { margin:4px 0; }
.empty { color:var(--muted); }
footer { color:var(--muted); font-size:12px; margin-top:40px;
  border-top:1px solid var(--border); padding-top:16px; }
"""
